### ISSUE TITLE
BEWARE: this package breaks node-gyp on node 6.9

### ISSUE THREAD

**Issue by joniba** [ChrisWren/grunt-nodemon#71]
After many hours of trying to understand why node-gyp builds of various packages were failing after upgrade to node 6.9 LTS (boron), I finally found this package to be the cause. I highly recommend avoiding this package until this issue is fixed!
Node-gyp build of packages like mmmagic, bcrypt and memwatch will all fail with the mysterious error:

**/usr/src/app/node_modules/.bin/touch: 1: /usr/src/app/node_modules/.bin/touch: Syntax error: "(" unexpected**

For posterity and for other desperate google searchers, here is an example of a full error log:

> mmmagic@0.4.5 install /usr/src/app/node_modules/mmmagic
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.9.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.9.1/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/src/app/node_modules/mmmagic/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/src/app/node_modules/mmmagic',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/src/app/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
/usr/src/app/node_modules/.bin/touch: 1: /usr/src/app/node_modules/.bin/touch: Syntax error: "(" unexpected
deps/libmagic/libmagic.target.mk:132: recipe for target 'Release/obj.target/libmagic/deps/libmagic/src/apprentice.o' failed
make: *** [Release/obj.target/libmagic/deps/libmagic/src/apprentice.o] Error 2
make: Leaving directory '/usr/src/app/node_modules/mmmagic/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.17-boot2docker
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /usr/src/app/node_modules/mmmagic
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm info lifecycle mmmagic@0.4.5~install: Failed to exec install script

**Comment by troggy** [comment]
god bless you, man!
